#!/bin/bash
## usage: ./bred.bash message.bred breddir <src
spec=$1
brdir=$2


#synonyms

# when released...
pattern=pattern_${RANDOM}

# for now, during bootstrap
fname=${pattern}

# compile (generate) matcher/replacer
${bdir}/bred-generate.bash ${fname} ${spec} ${bdir}
# apply matcher/replacer to source
${bdir}/bred-apply.bash ${fname} ${bdir}

rm -f ${fname}.ohm ${fname}.fab
